(in-package #:flegrea)

(defclass input-state ()
  ((teclas :initform (make-hash-table :test #'eq) :reader %teclas-atuais)
   (teclas-anteriores :initform (make-hash-table :test #'eq) :reader %teclas-anteriores)
   (botoes :initform (make-hash-table :test #'eq) :reader %botoes-atuais)
   (botoes-anteriores :initform (make-hash-table :test #'eq) :reader %botoes-anteriores)
   (cursor :initform (make-vector2) :accessor cursor-position)
   (delta-do-cursor :initform (make-vector2) :accessor cursor-delta)
   (roda :initform 0.0f0 :accessor wheel-delta)
   (modificadores-atuais :initform nil :accessor modifiers)
   (ouvintes :initform nil :accessor %ouvintes-de-entrada)
   (eventos :initform nil :accessor %eventos-de-entrada)))

(defun make-input-state ()
  "Cria um estado de entrada independente."
  (make-instance 'input-state))

(defun %copiar-tabela-booleana (origem destino)
  (clrhash destino)
  (maphash (lambda (chave valor) (setf (gethash chave destino) valor)) origem)
  destino)

(defun %registrar-evento-de-entrada (estado tipo codigo &optional valor)
  (push (list :type tipo :code codigo :value valor) (%eventos-de-entrada estado)))

(defun %definir-tecla (estado tecla pressionada)
  (setf (gethash tecla (%teclas-atuais estado)) pressionada)
  (%registrar-evento-de-entrada estado :key tecla pressionada))

(defun %definir-botao (estado botao pressionado)
  (setf (gethash botao (%botoes-atuais estado)) pressionado)
  (%registrar-evento-de-entrada estado :mouse-button botao pressionado))

(defun %definir-cursor (estado x y)
  (set-vector2 (cursor-delta estado) (- x (flegrea:x (cursor-position estado)))
               (- y (flegrea:y (cursor-position estado))))
  (set-vector2 (cursor-position estado) x y)
  (%registrar-evento-de-entrada estado :cursor nil (clone (cursor-position estado))))

(defun %adicionar-roda (estado deslocamento)
  (incf (wheel-delta estado) (coerce deslocamento 'single-float))
  (%registrar-evento-de-entrada estado :wheel nil deslocamento))

(defun poll-input (state)
  "Fecha as transições de entrada e despacha eventos acumulados."
  (dolist (evento (nreverse (%eventos-de-entrada state)))
    (dolist (ouvinte (reverse (%ouvintes-de-entrada state))) (funcall ouvinte evento state)))
  (setf (%eventos-de-entrada state) nil)
  state)

(defun key-pressed-p (state key)
  "Informa se uma tecla foi pressionada neste frame."
  (and (gethash key (%teclas-atuais state))
       (not (gethash key (%teclas-anteriores state)))))

(defun key-released-p (state key)
  "Informa se uma tecla foi liberada neste frame."
  (and (gethash key (%teclas-anteriores state))
       (not (gethash key (%teclas-atuais state)))))

(defun mouse-down-p (state button)
  "Informa se um botão do mouse está pressionado."
  (not (null (gethash button (%botoes-atuais state)))))
(defun mouse-pressed-p (state button)
  "Informa se um botão do mouse foi pressionado neste frame."
  (and (gethash button (%botoes-atuais state))
       (not (gethash button (%botoes-anteriores state)))))
(defun mouse-released-p (state button)
  "Informa se um botão do mouse foi liberado neste frame."
  (and (gethash button (%botoes-anteriores state))
       (not (gethash button (%botoes-atuais state)))))

(defun add-input-listener (state listener)
  "Adiciona um ouvinte de eventos de entrada."
  (check-type listener function) (pushnew listener (%ouvintes-de-entrada state)) state)
(defun remove-input-listener (state listener)
  "Remove um ouvinte de eventos de entrada."
  (setf (%ouvintes-de-entrada state) (remove listener (%ouvintes-de-entrada state))) state)

(defun %finalizar-frame-de-entrada (estado)
  (%copiar-tabela-booleana (%teclas-atuais estado) (%teclas-anteriores estado))
  (%copiar-tabela-booleana (%botoes-atuais estado) (%botoes-anteriores estado))
  (set-vector2 (cursor-delta estado) 0 0)
  (setf (wheel-delta estado) 0.0f0)
  estado)

(defclass intersection ()
  ((distancia :initarg :distance :reader intersection-distance)
   (ponto :initarg :point :reader intersection-point)
   (normal-da-face :initarg :normal :initform nil :reader intersection-normal)
   (coordenada-uv :initarg :uv :initform nil :reader intersection-uv)
   (objeto :initarg :object :reader intersection-object)
   (face :initarg :face :initform nil :reader intersection-face)
   (instancia :initarg :instance :initform nil :reader intersection-instance)))

(defclass raycaster ()
  ((raio :initarg :ray :accessor %raycaster-ray)
   (perto :initarg :near :initform 0.0f0 :accessor near)
   (longe :initarg :far :initform most-positive-single-float :accessor far)
   (camadas :initarg :layers :initform 1 :accessor layers)
   (limiar-de-linha :initarg :line-threshold :initform 0.1f0 :accessor %limiar-de-linha)
   (limiar-de-ponto :initarg :point-threshold :initform 0.1f0 :accessor %limiar-de-ponto)))

(defun make-raycaster (&key (origin (make-vector3)) (direction (make-vector3 0 0 -1))
                          (near 0.0f0) (far most-positive-single-float)
                          (line-threshold 0.1f0) (point-threshold 0.1f0))
  "Cria um lançador de raios."
  (make-instance 'raycaster :ray (make-ray origin direction) :near near :far far
                 :line-threshold line-threshold :point-threshold point-threshold))

(defun set-ray-from-camera (raycaster ndc camera)
  "Configura o raio por coordenadas normalizadas da câmera."
  (update-matrix-world camera)
  (let* ((inversa-projecao (matrix-invert (clone (projection-matrix camera))))
         (perto (make-vector3 (x ndc) (y ndc) -1.0f0))
         (longe (make-vector3 (x ndc) (y ndc) 1.0f0)))
    (apply-matrix4 perto inversa-projecao)
    (apply-matrix4 longe inversa-projecao)
    (apply-matrix4 perto (matrix-world camera))
    (apply-matrix4 longe (matrix-world camera))
    (copy-from (origin (%raycaster-ray raycaster)) perto)
    (copy-from (direction (%raycaster-ray raycaster)) (subtract longe perto))
    (normalize (direction (%raycaster-ray raycaster))))
  raycaster)

(defun %distancia-entre-pontos (a b)
  (vector-length (subtract (clone a) b)))

(defun %intersecoes-de-malha (raycaster objeto &optional instancia)
  (let* ((geometria (geometry objeto)) (posicao (get-attribute geometria :position))
         (dados (and posicao (attribute-array posicao))) (atributo-indice (index geometria))
         (indices (and atributo-indice (attribute-array atributo-indice)))
         (atributo-uv (get-attribute geometria :uv))
         (dados-uv (and atributo-uv (attribute-array atributo-uv)))
         (matriz (if instancia
                     (matrix-multiply (clone (matrix-world objeto))
                                      (aref (instance-matrices objeto) instancia))
                     (matrix-world objeto)))
         (inversa (matrix-invert (clone matriz)))
         (origem-local (apply-matrix4 (clone (origin (%raycaster-ray raycaster))) inversa))
         (fim-local (apply-matrix4
                     (add (clone (origin (%raycaster-ray raycaster)))
                          (direction (%raycaster-ray raycaster))) inversa))
         (raio-local (make-ray origem-local (subtract fim-local origem-local)))
         (resultados nil))
    (when dados
      (labels ((indice (cursor) (if indices (aref indices cursor) cursor))
               (ponto (indice)
                 (let ((base (* indice 3)))
                   (make-vector3 (aref dados base) (aref dados (1+ base)) (aref dados (+ base 2)))))
               (coordenada-uv (indice)
                 (let ((base (* indice 2)))
                   (make-vector2 (aref dados-uv base) (aref dados-uv (1+ base)))))
               (interpolar-uv (acerto a b c ia ib ic)
                 (when dados-uv
                   (let* ((ab (subtract (clone b) a)) (ac (subtract (clone c) a))
                          (ap (subtract (clone acerto) a))
                          (d00 (dot ab ab)) (d01 (dot ab ac)) (d11 (dot ac ac))
                          (d20 (dot ap ab)) (d21 (dot ap ac))
                          (denominador (- (* d00 d11) (* d01 d01))))
                     (unless (< (abs denominador) 1.0e-8)
                       (let* ((peso-b (/ (- (* d11 d20) (* d01 d21)) denominador))
                              (peso-c (/ (- (* d00 d21) (* d01 d20)) denominador))
                              (peso-a (- 1.0f0 peso-b peso-c))
                              (uv-a (coordenada-uv ia)) (uv-b (coordenada-uv ib))
                              (uv-c (coordenada-uv ic)))
                         (make-vector2 (+ (* peso-a (x uv-a)) (* peso-b (x uv-b)) (* peso-c (x uv-c)))
                                       (+ (* peso-a (y uv-a)) (* peso-b (y uv-b)) (* peso-c (y uv-c))))))))))
        (loop for cursor from 0 below (if indices (length indices) (/ (length dados) 3)) by 3
              for face from 0 do
          (let* ((ia (indice cursor)) (ib (indice (1+ cursor))) (ic (indice (+ cursor 2)))
                 (a (ponto ia)) (b (ponto ib)) (c (ponto ic))
                 (acerto (intersect-ray-triangle raio-local (make-triangle a b c))))
            (when acerto
              (let* ((mundial (apply-matrix4 acerto matriz))
                     (distancia (%distancia-entre-pontos mundial (origin (%raycaster-ray raycaster))))
                     (normal-local (normalize (cross (subtract (clone b) a)
                                                    (subtract (clone c) a))))
                     (normal-mundial
                       (normalize
                        (apply-matrix3 normal-local (set-normal-matrix3 (make-matrix3) matriz))))
                     (uv (interpolar-uv acerto a b c ia ib ic)))
                (when (<= (near raycaster) distancia (far raycaster))
                  (push (make-instance 'intersection :distance distancia :point mundial
                                       :normal normal-mundial :uv uv :object objeto :face face
                                       :instance instancia)
                        resultados)))))))
    resultados)))

(defun %intersecoes-de-pontos (raycaster objeto)
  (let* ((dados (attribute-array (get-attribute (geometry objeto) :position)))
         (resultados nil))
    (loop for cursor from 0 below (length dados) by 3 for indice from 0 do
      (let* ((ponto (apply-matrix4 (make-vector3 (aref dados cursor) (aref dados (1+ cursor))
                                                 (aref dados (+ cursor 2)))
                                    (matrix-world objeto)))
             (distancia-raio (distance-to-point (%raycaster-ray raycaster) ponto))
             (distancia (%distancia-entre-pontos ponto (origin (%raycaster-ray raycaster)))))
        (when (and (<= distancia-raio (%limiar-de-ponto raycaster))
                   (<= (near raycaster) distancia (far raycaster)))
          (push (make-instance 'intersection :distance distancia :point ponto
                               :object objeto :face indice) resultados))))
    resultados))

(defun %ponto-mais-proximo-do-segmento (raio a b)
  (let* ((direcao (direction raio)) (segmento (subtract (clone b) a))
         (origem-relativa (subtract (clone (origin raio)) a))
         (aa (dot direcao direcao)) (bb (dot direcao segmento))
         (cc (dot segmento segmento)) (dd (dot direcao origem-relativa))
         (ee (dot segmento origem-relativa))
         (denominador (- (* aa cc) (* bb bb)))
         (fator-segmento (if (< (abs denominador) 1.0e-8)
                             0.0f0
                             (/ (- (* aa ee) (* bb dd)) denominador))))
    (setf fator-segmento (max 0.0f0 (min 1.0f0 fator-segmento)))
    (let* ((ponto-segmento (add (clone a) (multiply-scalar segmento fator-segmento)))
           (fator-raio (max 0.0f0 (/ (dot (subtract (clone ponto-segmento)
                                                     (origin raio)) direcao)
                                      aa)))
           (ponto-raio (ray-at raio fator-raio)))
      (values ponto-segmento (%distancia-entre-pontos ponto-segmento ponto-raio)
              fator-raio))))

(defun %intersecoes-de-linha (raycaster objeto)
  (let* ((atributo (get-attribute (geometry objeto) :position))
         (dados (and atributo (attribute-array atributo)))
         (atributo-indice (index (geometry objeto)))
         (indices (and atributo-indice (attribute-array atributo-indice)))
         (quantidade (if indices (length indices) (if dados (/ (length dados) 3) 0)))
         (passo (if (typep objeto 'line-segments) 2 1)) (resultados nil))
    (labels ((indice (cursor) (if indices (aref indices cursor) cursor))
             (ponto (cursor)
               (let ((base (* (indice cursor) 3)))
                 (apply-matrix4
                  (make-vector3 (aref dados base) (aref dados (1+ base))
                                (aref dados (+ base 2)))
                  (matrix-world objeto)))))
      (loop for cursor from 0 below (1- quantidade) by passo for segmento from 0 do
        (multiple-value-bind (ponto distancia-do-raio fator-raio)
            (%ponto-mais-proximo-do-segmento (%raycaster-ray raycaster)
                                             (ponto cursor) (ponto (1+ cursor)))
          (when (and (<= distancia-do-raio (%limiar-de-linha raycaster))
                     (<= (near raycaster) fator-raio (far raycaster)))
            (push (make-instance 'intersection :distance fator-raio :point ponto
                                 :object objeto :face segmento)
                  resultados)))))
    resultados))

(defun %intersecoes-de-sprite (raycaster objeto)
  (let* ((matriz (elements (matrix-world objeto)))
         (centro (make-vector3 (aref matriz 12) (aref matriz 13) (aref matriz 14)))
         (escala-x (sqrt (+ (expt (aref matriz 0) 2) (expt (aref matriz 1) 2)
                            (expt (aref matriz 2) 2))))
         (escala-y (sqrt (+ (expt (aref matriz 4) 2) (expt (aref matriz 5) 2)
                            (expt (aref matriz 6) 2))))
         (raio (* 0.7071068f0 (max escala-x escala-y)))
         (origem-relativa (subtract (clone (origin (%raycaster-ray raycaster))) centro))
         (direcao (direction (%raycaster-ray raycaster)))
         (b (dot origem-relativa direcao))
         (c (- (dot origem-relativa origem-relativa) (* raio raio)))
         (discriminante (- (* b b) c)))
    (when (not (minusp discriminante))
      (let ((distancia (- (- b) (sqrt discriminante))))
        (when (minusp distancia) (setf distancia (+ (- b) (sqrt discriminante))))
        (when (<= (near raycaster) distancia (far raycaster))
          (list (make-instance 'intersection :distance distancia
                               :point (ray-at (%raycaster-ray raycaster) distancia)
                               :object objeto)))))))

(defun intersect-object (raycaster object &key (recursive t))
  "Retorna interseções ordenadas por distância."
  (let ((resultados nil))
    (labels ((visitar (objeto)
               (when (and (visible objeto) (not (zerop (logand (layers raycaster) (layers objeto)))))
                 (cond
                   ((typep objeto 'instanced-mesh)
                    (dotimes (indice (instance-count objeto))
                      (setf resultados (nconc (%intersecoes-de-malha raycaster objeto indice) resultados))))
                   ((typep objeto 'mesh)
                    (setf resultados (nconc (%intersecoes-de-malha raycaster objeto) resultados)))
                   ((typep objeto 'points)
                    (setf resultados (nconc (%intersecoes-de-pontos raycaster objeto) resultados)))
                   ((typep objeto 'line)
                    (setf resultados (nconc (%intersecoes-de-linha raycaster objeto) resultados)))
                   ((typep objeto 'sprite)
                    (setf resultados (nconc (%intersecoes-de-sprite raycaster objeto) resultados))))
                 (when recursive (dolist (filho (children objeto)) (visitar filho))))))
      (visitar object))
    (stable-sort resultados #'< :key #'intersection-distance)))

(defclass orbit-controls ()
  ((camera :initarg :camera :reader %camera-dos-controles)
   (entrada :initarg :input :reader %entrada-dos-controles)
   (alvo :initarg :target :initform (make-vector3) :accessor controls-target)
   (habilitado :initarg :enabled :initform t :accessor controls-enabled)
   (amortecimento :initarg :enable-damping :initform t :accessor enable-damping)
   (fator-de-amortecimento :initarg :damping-factor :initform 0.08f0 :accessor damping-factor)
   (distancia-minima :initarg :min-distance :initform 0.1f0 :accessor min-distance)
   (distancia-maxima :initarg :max-distance :initform most-positive-single-float :accessor max-distance)
   (angulo-polar-minimo :initarg :min-polar-angle :initform 0.0f0 :accessor min-polar-angle)
   (angulo-polar-maximo :initarg :max-polar-angle :initform pi :accessor max-polar-angle)
   (velocidade-angular :initform (make-vector2) :accessor %velocidade-angular)
   (velocidade-de-pan :initform (make-vector3) :accessor %velocidade-de-pan)
   (velocidade-de-zoom :initform 0.0f0 :accessor %velocidade-de-zoom)))

(defun make-orbit-controls (camera input &rest options &key &allow-other-keys)
  "Cria controles orbitais para uma câmera."
  (apply #'make-instance 'orbit-controls :camera camera :input input options))

(defun controls-update (controls delta)
  "Atualiza rotação, pan e dolly dos controles orbitais."
  (declare (ignore delta))
  (when (controls-enabled controls)
    (let ((entrada (%entrada-dos-controles controls)))
      (when (mouse-down-p entrada :left)
        (incf (x (%velocidade-angular controls)) (* -0.005f0 (x (cursor-delta entrada))))
        (incf (y (%velocidade-angular controls)) (* -0.005f0 (y (cursor-delta entrada)))))
      (when (or (mouse-down-p entrada :right) (mouse-down-p entrada :middle))
        (let* ((camera (%camera-dos-controles controls))
               (frente (normalize (subtract (clone (controls-target controls))
                                             (position camera))))
               (direita (normalize (cross (clone frente) (make-vector3 0 1 0))))
               (acima (normalize (cross (clone direita) frente)))
               (escala (* 0.002f0
                          (max 1.0f0 (vector-length
                                      (subtract (clone (position camera))
                                                (controls-target controls)))))))
          (add (%velocidade-de-pan controls)
               (multiply-scalar direita (* -1.0f0 escala (x (cursor-delta entrada)))))
          (add (%velocidade-de-pan controls)
               (multiply-scalar acima (* escala (y (cursor-delta entrada)))))))
      (incf (%velocidade-de-zoom controls) (* 0.12f0 (wheel-delta entrada))))
    (add (controls-target controls) (%velocidade-de-pan controls))
    (let* ((camera (%camera-dos-controles controls))
           (deslocamento (subtract (clone (position camera)) (controls-target controls)))
           (raio (max (min-distance controls)
                      (min (max-distance controls)
                           (* (vector-length deslocamento)
                              (exp (%velocidade-de-zoom controls))))))
           (azimute (+ (atan (x deslocamento) (z deslocamento))
                       (x (%velocidade-angular controls))))
           (polar (max (min-polar-angle controls)
                       (min (max-polar-angle controls)
                            (+ (acos (/ (y deslocamento) (max 1.0e-6 (vector-length deslocamento))))
                               (y (%velocidade-angular controls)))))))
      (set-position camera (+ (x (controls-target controls)) (* raio (sin polar) (sin azimute)))
                    (+ (y (controls-target controls)) (* raio (cos polar)))
                    (+ (z (controls-target controls)) (* raio (sin polar) (cos azimute))))
      (look-at camera (controls-target controls))
      (if (enable-damping controls)
          (progn (multiply-scalar (%velocidade-angular controls)
                                  (- 1.0f0 (damping-factor controls)))
                 (setf (%velocidade-de-zoom controls)
                       (* (%velocidade-de-zoom controls) (- 1.0f0 (damping-factor controls))))
                 (multiply-scalar (%velocidade-de-pan controls)
                                  (- 1.0f0 (damping-factor controls))))
          (progn (set-vector2 (%velocidade-angular controls) 0 0)
                 (set-vector3 (%velocidade-de-pan controls) 0 0 0)
                 (setf (%velocidade-de-zoom controls) 0.0f0)))))
  controls)
