(in-package #:flegrea)

(defclass circle-geometry (buffer-geometry) ())
(defclass ring-geometry (buffer-geometry) ())
(defclass cylinder-geometry (buffer-geometry) ())
(defclass cone-geometry (cylinder-geometry) ())
(defclass torus-geometry (buffer-geometry) ())
(defclass capsule-geometry (buffer-geometry) ())
(defclass edges-geometry (buffer-geometry) ())
(defclass wireframe-geometry (edges-geometry) ())

(defun add-group (geometria inicio quantidade material-index)
  "Adiciona um grupo de desenho a uma geometria."
  (%verificar-recurso-vivo geometria :add-group)
  (unless (and (integerp inicio) (not (minusp inicio)) (integerp quantidade)
               (not (minusp quantidade)) (integerp material-index) (not (minusp material-index)))
    (error 'validation-error :message "Os dados do grupo de geometria são inválidos."))
  (setf (geometry-groups geometria)
        (append (geometry-groups geometria)
                (list (list :start inicio :count quantidade :material-index material-index))))
  geometria)

(defun clear-groups (geometria)
  "Remove todos os grupos de uma geometria."
  (setf (geometry-groups geometria) nil) geometria)

(defun set-draw-range (geometria inicio &optional quantidade)
  "Define o intervalo de elementos desenhado."
  (unless (and (integerp inicio) (not (minusp inicio))
               (or (null quantidade) (and (integerp quantidade) (not (minusp quantidade)))))
    (error 'validation-error :message "O intervalo de desenho é inválido."))
  (setf (draw-range geometria) (cons inicio quantidade)) geometria)

(defun compute-bounding-box (geometria)
  "Calcula a caixa limite pelas posições da geometria."
  (let ((atributo (get-attribute geometria :position)) (caixa (make-box3)))
    (unless (and atributo (= (item-size atributo) 3))
      (error 'validation-error :message "A geometria precisa de posições tridimensionais."))
    (let ((dados (attribute-array atributo)))
      (loop for indice from 0 below (length dados) by 3 do
        (expand-by-point caixa (make-vector3 (aref dados indice) (aref dados (1+ indice))
                                             (aref dados (+ indice 2))))))
    (setf (bounding-box geometria) caixa)))

(defun compute-bounding-sphere (geometria)
  "Calcula uma esfera limite pelas posições da geometria."
  (let* ((caixa (or (bounding-box geometria) (compute-bounding-box geometria)))
         (centro (multiply-scalar (add (clone (min-point caixa)) (max-point caixa)) 0.5f0))
         (atributo (get-attribute geometria :position))
         (dados (attribute-array atributo))
         (raio-quadrado 0.0f0))
    (loop for indice from 0 below (length dados) by 3 do
      (let ((ponto (make-vector3 (aref dados indice) (aref dados (1+ indice)) (aref dados (+ indice 2)))))
        (setf raio-quadrado (max raio-quadrado
                                 (length-squared (subtract ponto centro))))))
    (setf (bounding-sphere geometria) (make-sphere centro (sqrt raio-quadrado)))))

(defmethod dispose ((geometria buffer-geometry))
  (unless (disposed-p geometria)
    (clrhash (attributes geometria))
    (setf (index geometria) nil (geometry-groups geometria) nil))
  (call-next-method))

(defun %preencher-geometria (classe posicoes normais uvs indices &optional (modo :triangles))
  (let ((geometria (make-instance classe :primitive-mode modo)))
    (set-attribute geometria :position (make-buffer-attribute posicoes 3))
    (when normais (set-attribute geometria :normal (make-buffer-attribute normais 3)))
    (when uvs (set-attribute geometria :uv (make-buffer-attribute uvs 2)))
    (when indices (set-index geometria indices))
    geometria))

(defun make-circle-geometry (&key (radius 1.0f0) (segments 32) (theta-start 0.0f0)
                                  (theta-length (* 2.0f0 pi)))
  "Cria um disco no plano XY."
  (unless (and (plusp radius) (integerp segments) (>= segments 3))
    (error 'validation-error :message "Os parâmetros do círculo são inválidos."))
  (let ((posicoes (list 0.0f0 0.0f0 0.0f0)) (normais (list 0.0f0 0.0f0 1.0f0))
        (uvs (list 0.5f0 0.5f0)) (indices nil))
    (dotimes (i (1+ segments))
      (let* ((angulo (+ theta-start (* theta-length (/ i segments))))
             (px (* radius (cos angulo))) (py (* radius (sin angulo))))
        (setf posicoes (nconc posicoes (list px py 0.0f0))
              normais (nconc normais (list 0.0f0 0.0f0 1.0f0))
              uvs (nconc uvs (list (+ 0.5f0 (/ px (* 2 radius)))
                                    (+ 0.5f0 (/ py (* 2 radius))))))))
    (dotimes (i segments) (setf indices (nconc indices (list 0 (1+ i) (+ i 2)))))
    (%preencher-geometria 'circle-geometry posicoes normais uvs indices)))

(defun make-ring-geometry (&key (inner-radius 0.5f0) (outer-radius 1.0f0) (segments 32))
  "Cria um anel no plano XY."
  (unless (and (<= 0 inner-radius) (> outer-radius inner-radius)
               (integerp segments) (>= segments 3))
    (error 'validation-error :message "Os parâmetros do anel são inválidos."))
  (let ((posicoes nil) (normais nil) (uvs nil) (indices nil))
    (dotimes (i (1+ segments))
      (let ((angulo (* 2 pi (/ i segments))))
        (dolist (raio (list inner-radius outer-radius))
          (let ((px (* raio (cos angulo))) (py (* raio (sin angulo))))
            (setf posicoes (nconc posicoes (list px py 0.0f0))
                  normais (nconc normais (list 0.0f0 0.0f0 1.0f0))
                  uvs (nconc uvs (list (+ 0.5f0 (/ px (* 2 outer-radius)))
                                        (+ 0.5f0 (/ py (* 2 outer-radius))))))))))
    (dotimes (i segments)
      (let ((a (* i 2)) (b (1+ (* i 2))) (c (+ (* i 2) 2)) (d (+ (* i 2) 3)))
        (setf indices (nconc indices (list a b c b d c)))))
    (%preencher-geometria 'ring-geometry posicoes normais uvs indices)))

(defun %criar-lateral-cilindrica (classe raio-superior raio-inferior altura segmentos)
  (let ((posicoes nil) (normais nil) (uvs nil) (indices nil)
        (meia-altura (/ altura 2.0f0))
        (inclinacao (/ (- raio-inferior raio-superior) altura)))
    (dotimes (linha 2)
      (let ((raio (if (zerop linha) raio-superior raio-inferior))
            (py (if (zerop linha) meia-altura (- meia-altura))))
        (dotimes (i (1+ segmentos))
          (let* ((u (/ i segmentos)) (angulo (* u 2 pi))
                 (nx (cos angulo)) (nz (sin angulo))
                 (n (normalize (make-vector3 nx inclinacao nz))))
            (setf posicoes (nconc posicoes (list (* raio nx) py (* raio nz)))
                  normais (nconc normais (list (x n) (y n) (z n)))
                  uvs (nconc uvs (list u (- 1 linha))))))))
    (dotimes (i segmentos)
      (let ((a i) (b (+ i (1+ segmentos))) (c (1+ i)) (d (+ i segmentos 2)))
        (setf indices (nconc indices (list a b c c b d)))))
    (%preencher-geometria classe posicoes normais uvs indices)))

(defun make-cylinder-geometry (&key (radius-top 1.0f0) (radius-bottom 1.0f0)
                                    (height 1.0f0) (radial-segments 32))
  "Cria a superfície lateral de um cilindro ou tronco de cone."
  (unless (and (>= radius-top 0) (>= radius-bottom 0) (plusp height)
               (integerp radial-segments) (>= radial-segments 3)
               (plusp (+ radius-top radius-bottom)))
    (error 'validation-error :message "Os parâmetros do cilindro são inválidos."))
  (%criar-lateral-cilindrica 'cylinder-geometry radius-top radius-bottom height radial-segments))

(defun make-cone-geometry (&key (radius 1.0f0) (height 1.0f0) (radial-segments 32))
  "Cria a superfície lateral de um cone."
  (%criar-lateral-cilindrica 'cone-geometry 0.0f0 radius height radial-segments))

(defun make-torus-geometry (&key (radius 1.0f0) (tube 0.4f0) (radial-segments 16)
                                 (tubular-segments 48))
  "Cria um toro UV indexado."
  (unless (and (plusp radius) (plusp tube) (>= radial-segments 3) (>= tubular-segments 3))
    (error 'validation-error :message "Os parâmetros do toro são inválidos."))
  (let ((posicoes nil) (normais nil) (uvs nil) (indices nil))
    (dotimes (j (1+ radial-segments))
      (dotimes (i (1+ tubular-segments))
        (let* ((u (* 2 pi (/ i tubular-segments))) (v (* 2 pi (/ j radial-segments)))
               (cv (cos v)) (sv (sin v)) (cu (cos u)) (su (sin u)))
          (setf posicoes (nconc posicoes (list (* (+ radius (* tube cv)) cu)
                                                (* tube sv) (* (+ radius (* tube cv)) su)))
                normais (nconc normais (list (* cv cu) sv (* cv su)))
                uvs (nconc uvs (list (/ i tubular-segments) (/ j radial-segments)))))))
    (dotimes (j radial-segments)
      (dotimes (i tubular-segments)
        (let* ((a (+ i (* j (1+ tubular-segments)))) (b (+ a (1+ tubular-segments)))
               (c (1+ b)) (d (1+ a)))
          (setf indices (nconc indices (list a b d b c d))))))
    (%preencher-geometria 'torus-geometry posicoes normais uvs indices)))

(defun make-capsule-geometry (&key (radius 0.5f0) (length 1.0f0) (segments 16))
  "Cria uma cápsula UV aproximada."
  (let ((base (make-sphere-geometry :radius radius
                                    :width-segments (* 2 segments)
                                    :height-segments segments)))
    (change-class base 'capsule-geometry)
    (let ((dados (attribute-array (get-attribute base :position))))
      (loop for indice from 1 below (length dados) by 3 do
        (incf (aref dados indice) (if (plusp (aref dados indice))
                                      (/ length 2.0f0) (- (/ length 2.0f0))))))
    base))

(defun make-edges-geometry (source)
  "Cria segmentos para todas as arestas indexadas de uma geometria."
  (let* ((posicao (get-attribute source :position))
         (dados (and posicao (attribute-array posicao)))
         (indice (index source))
         (indices (and indice (attribute-array indice)))
         (arestas (make-hash-table :test #'equal)) (saida nil))
    (unless dados (error 'validation-error :message "A geometria não possui posições."))
    (labels ((vertice (i) (if indices (aref indices i) i))
             (registrar (a b)
               (let ((chave (if (< a b) (cons a b) (cons b a))))
                 (setf (gethash chave arestas) t))))
      (loop for i from 0 below (if indices (length indices) (/ (length dados) 3)) by 3 do
        (let ((a (vertice i)) (b (vertice (1+ i))) (c (vertice (+ i 2))))
          (registrar a b) (registrar b c) (registrar c a)))
      (maphash (lambda (chave valor)
                 (declare (ignore valor))
                 (dolist (v (list (car chave) (cdr chave)))
                   (let ((base (* v 3)))
                     (setf saida (nconc saida (list (aref dados base) (aref dados (1+ base))
                                                    (aref dados (+ base 2))))))))
               arestas))
    (%preencher-geometria 'edges-geometry saida nil nil nil :lines)))

(defun make-wireframe-geometry (source)
  "Cria uma geometria de arame a partir de triângulos."
  (change-class (make-edges-geometry source) 'wireframe-geometry))
