(in-package #:flegrea)

(defclass render-item ()
  ((objeto :initarg :object :reader %objeto-do-item)
   (geometria :initarg :geometry :reader %geometria-do-item)
   (material-do-item :initarg :material :reader %material-do-item)
   (distancia :initarg :distance :reader %distancia-do-item)
   (ordem :initarg :order :reader %ordem-do-item)
   (grupo :initarg :group :initform nil :reader %grupo-do-item)))

(defclass render-list ()
  ((opacos :initform nil :accessor opaque-items)
   (transparentes :initform nil :accessor transparent-items)))

(defclass renderer-stats ()
  ((chamadas :initform 0 :accessor draw-calls)
   (triangulos :initform 0 :accessor triangles-rendered)
   (objetos :initform 0 :accessor objects-rendered)
   (cortados :initform 0 :accessor objects-culled)))

(defun %posicao-mundial-do-objeto (objeto)
  (let ((dados (elements (matrix-world objeto))))
    (make-vector3 (aref dados 12) (aref dados 13) (aref dados 14))))

(defun %escala-maxima-mundial (objeto)
  (let ((m (elements (matrix-world objeto))))
    (max (sqrt (+ (* (aref m 0) (aref m 0)) (* (aref m 1) (aref m 1)) (* (aref m 2) (aref m 2))))
         (sqrt (+ (* (aref m 4) (aref m 4)) (* (aref m 5) (aref m 5)) (* (aref m 6) (aref m 6))))
         (sqrt (+ (* (aref m 8) (aref m 8)) (* (aref m 9) (aref m 9)) (* (aref m 10) (aref m 10)))))))

(defun %visivel-no-frustum-p (objeto frustum)
  (or (not (frustum-culled objeto))
      (let* ((geometria (and (typep objeto '(or mesh line points)) (geometry objeto)))
             (limite (and geometria
                          (or (bounding-sphere geometria) (compute-bounding-sphere geometria)))))
        (or (null limite)
            (let ((mundial (make-sphere
                            (apply-matrix4 (clone (center limite)) (matrix-world objeto))
                            (* (radius limite) (%escala-maxima-mundial objeto)))))
              (intersects-sphere-p frustum mundial))))))

(defun %materiais-do-objeto (objeto)
  (let ((valor (material objeto)))
    (if (listp valor) valor (list valor))))

(defun %item-transparente-p (material)
  (or (transparent material) (< (opacity material) 1.0f0)
      (member (alpha-mode material) '(:blend :mask))
      (and (typep material 'mesh-physical-material) (plusp (transmission material)))))

(defun build-render-list (scene camera &optional stats)
  "Constrói listas estáveis de objetos opacos e transparentes."
  (update-matrix-world scene)
  (unless (parent camera) (update-matrix-world camera))
  (let* ((lista (make-instance 'render-list))
         (estatisticas (or stats (make-instance 'renderer-stats)))
         (matriz-vp (matrix-multiply (clone (projection-matrix camera)) (view-matrix camera)))
         (frustum (set-from-projection-matrix (make-frustum) matriz-vp))
         (camera-pos (%posicao-mundial-do-objeto camera)))
    (labels ((visitar (objeto ancestral-visivel)
               (let ((agora (and ancestral-visivel (visible objeto))))
                 (when (and agora (typep objeto '(or mesh line points sprite))
                            (layers-match-p objeto camera))
                   (if (%visivel-no-frustum-p objeto frustum)
                       (let* ((distancia (length-squared
                                         (subtract (%posicao-mundial-do-objeto objeto) camera-pos)))
                              (materiais (%materiais-do-objeto objeto))
                              (grupos (and (typep objeto '(or mesh line points))
                                           (geometry-groups (geometry objeto)))))
                         (if grupos
                             (dolist (grupo grupos)
                               (let* ((indice (getf grupo :material-index))
                                      (material (or (nth indice materiais) (first materiais)))
                                      (item (make-instance 'render-item :object objeto
                                                           :geometry (geometry objeto)
                                                           :material material :distance distancia
                                                           :order (render-order objeto) :group grupo)))
                                 (if (%item-transparente-p material)
                                     (push item (transparent-items lista))
                                     (push item (opaque-items lista)))))
                             (dolist (material materiais)
                               (let ((item (make-instance 'render-item :object objeto
                                                          :geometry (unless (typep objeto 'sprite)
                                                                      (geometry objeto))
                                                          :material material :distance distancia
                                                          :order (render-order objeto))))
                                 (if (%item-transparente-p material)
                                     (push item (transparent-items lista))
                                     (push item (opaque-items lista))))))
                         (incf (objects-rendered estatisticas)))
                       (incf (objects-culled estatisticas))))
                 (dolist (filho (children objeto)) (visitar filho agora)))))
      (visitar scene t))
    (setf (opaque-items lista)
          (stable-sort (nreverse (opaque-items lista))
                       (lambda (a b)
                         (or (< (%ordem-do-item a) (%ordem-do-item b))
                             (and (= (%ordem-do-item a) (%ordem-do-item b))
                                  (< (%distancia-do-item a) (%distancia-do-item b))))))
          (transparent-items lista)
          (stable-sort (nreverse (transparent-items lista))
                       (lambda (a b)
                         (or (< (%ordem-do-item a) (%ordem-do-item b))
                             (and (= (%ordem-do-item a) (%ordem-do-item b))
                                  (> (%distancia-do-item a) (%distancia-do-item b)))))))
    lista))
