(in-package #:flegrea.meta)

(defclass binding ()
  ((forma :initarg :form :reader %forma-vinculo)))

(defclass meta-node ()
  ((node-id :initarg :id :reader node-id)
   (node-type :initarg :type :reader node-type)
   (node-properties :initarg :properties :initform nil :accessor node-properties)
   (node-children :initarg :children :initform nil :accessor node-children)))

(defclass meta-scene ()
  ((raiz :initarg :root :reader %raiz-meta)
   (nos :initarg :nodes :reader %nos-meta)
   (forma :initarg :form :reader %forma-meta)))

(defclass scene-instance ()
  ((instance-scene :initarg :scene :accessor instance-scene)
   (instance-camera :initarg :camera :accessor instance-camera)
   (descricao :initarg :description :accessor %descricao-instancia)
   (objetos :initarg :objects :accessor %objetos-instancia)))

(defclass %contexto-instanciacao ()
  ((objetos :initarg :objects :reader %objetos-contexto)
   (descricao :initarg :description :reader %descricao-contexto)))

(defparameter *classes-de-no* (make-hash-table :test #'eq))
(defparameter *descricoes-de-cena* (make-hash-table :test #'equal))

(defun %tag (simbolo)
  (if (keywordp simbolo) simbolo (intern (string-upcase (symbol-name simbolo)) :keyword)))

(defun register-node-class (tag class &key properties bindable-properties child-policy resource-p)
  "Registra uma subclasse CLOS e seu contrato na DSL."
  (unless (subtypep class 'meta-node)
    (error 'validation-error :message "A classe registrada precisa herdar de meta-node."))
  (setf (gethash (%tag tag) *classes-de-no*)
        (list :class class :properties properties :bindable-properties bindable-properties
              :child-policy child-policy :resource-p resource-p))
  tag)

(eval-when (:load-toplevel :execute)
  (dolist (registro
           '((:scene (:active-camera :resources) :many nil)
             (:group () :many nil)
             (:mesh (:geometry :material) :many nil)
             (:perspective-camera (:fov :aspect :near :far :zoom) :many nil)
             (:orthographic-camera (:left :right :top :bottom :near :far :zoom) :many nil)
             (:ambient-light (:color :intensity) :none nil)
             (:directional-light (:color :intensity :target) :none nil)
             (:point-light (:color :intensity :distance :decay) :none nil)
             (:box-geometry (:width :height :depth :face-colors) :none t)
             (:sphere-geometry (:radius :width-segments :height-segments) :none t)
             (:plane-geometry (:width :height :width-segments :height-segments) :none t)
             (:buffer-geometry (:attributes :index) :none t)
             (:mesh-basic-material (:color :vertex-colors) :none t)
             (:mesh-standard-material (:color :roughness :metalness :emissive :vertex-colors) :none t)
             (:shader-material (:vertex-shader :fragment-shader :uniforms :side :depth-write) :none t)))
    (destructuring-bind (tag propriedades politica recurso-p) registro
      (register-node-class tag 'meta-node :properties
                           (append propriedades '(:name :visible :position :rotation :scale))
                           :bindable-properties
                           '(:position :rotation :scale :fov :aspect :zoom :color :intensity
                             :roughness :metalness :emissive :distance :decay :uniforms)
                           :child-policy politica :resource-p recurso-p))))

(defun bind (form)
  "Cria uma forma de binding para descrições construídas em runtime."
  (list :bind form))
(defun ref (id)
  "Cria uma referência por ID para descrições construídas em runtime."
  (list :ref id))

(defun node-property (node name &optional default)
  "Lê uma propriedade declarativa."
  (getf (node-properties node) name default))
(defun (setf node-property) (value node name &optional default)
  (declare (ignore default))
  (setf (getf (node-properties node) name) value))

(defun %operador-permitido-p (simbolo)
  (member (string-upcase (symbol-name simbolo))
          '("+" "-" "*" "/" "SIN" "COS" "TAN" "ABS" "MIN" "MAX" "CLAMP")
          :test #'string=))

(defun %validar-expressao (forma)
  (cond ((realp forma) t)
        ((member forma '(:time :delta) :test #'eq) t)
        ((and (consp forma) (symbolp (first forma)) (%operador-permitido-p (first forma)))
         (every #'%validar-expressao (rest forma)))
        (t (error 'validation-error :message "Um binding contém uma expressão que não pertence à AST permitida."))))

(defun %avaliar-expressao (forma tempo delta)
  (cond ((realp forma) (coerce forma 'single-float))
        ((eq forma :time) tempo)
        ((eq forma :delta) delta)
        (t
         (let ((argumentos (mapcar (lambda (item) (%avaliar-expressao item tempo delta)) (rest forma)))
               (nome (string-upcase (symbol-name (first forma)))))
           (cond ((string= nome "+") (reduce #'+ argumentos :initial-value 0.0f0))
                 ((string= nome "-") (if (= (length argumentos) 1) (- (first argumentos)) (reduce #'- argumentos)))
                 ((string= nome "*") (reduce #'* argumentos :initial-value 1.0f0))
                 ((string= nome "/") (reduce #'/ argumentos))
                 ((string= nome "SIN") (sin (first argumentos)))
                 ((string= nome "COS") (cos (first argumentos)))
                 ((string= nome "TAN") (tan (first argumentos)))
                 ((string= nome "ABS") (abs (first argumentos)))
                 ((string= nome "MIN") (reduce #'min argumentos))
                 ((string= nome "MAX") (reduce #'max argumentos))
                 ((string= nome "CLAMP") (max (second argumentos) (min (third argumentos) (first argumentos))))
                 (t (error 'validation-error :message "O operador do binding não é suportado.")))))))

(defun %nome-da-forma (forma)
  (and (consp forma) (symbolp (first forma)) (string-upcase (symbol-name (first forma)))))

(defun %normalizar-valor (valor)
  (let ((nome (%nome-da-forma valor)))
    (cond
      ((and nome (string= nome "BIND"))
       (unless (= (length valor) 2)
         (error 'validation-error :message "Bind precisa receber exatamente uma expressão."))
       (%validar-expressao (second valor))
       (make-instance 'binding :form (second valor)))
      ((and nome (string= nome "REF"))
       (unless (and (= (length valor) 2) (keywordp (second valor)))
         (error 'validation-error :message "Ref precisa receber exatamente um ID keyword."))
       (list :ref (second valor)))
      ((and nome (member nome '("VECTOR2" "VECTOR3" "VECTOR4" "EULER") :test #'string=))
       (cons (%tag (first valor)) (mapcar #'%normalizar-valor (rest valor))))
      ((consp valor) (mapcar #'%normalizar-valor valor))
      (t valor))))

(defun %separar-plist (itens)
  (unless (evenp (length itens))
    (error 'validation-error :message "As propriedades de um nó precisam formar uma plist completa."))
  itens)

(defun %parse-node (forma tabela)
  (unless (and (consp forma) (symbolp (first forma)))
    (error 'validation-error :message "Um nó da DSL precisa ser uma lista tipada."))
  (let* ((tipo (%tag (first forma))) (registro (gethash tipo *classes-de-no*)))
    (unless registro
      (error 'validation-error :message (format nil "O tipo de nó ~A não está registrado." tipo)))
    (let* ((plist (%separar-plist (rest forma))) (id (getf plist :id))
           (formas-filhos (or (getf plist :children) nil))
           (formas-recursos (or (getf plist :resources) nil))
           (permitidas (getf registro :properties)) (propriedades nil))
      (unless (keywordp id)
        (error 'validation-error :message "Todo nó persistente precisa de um ID keyword."))
      (when (gethash id tabela)
        (error 'validation-error :message (format nil "O ID ~A aparece mais de uma vez no metagrafo." id)))
      (loop for (chave valor) on plist by #'cddr do
        (unless (member chave (append '(:id :children) permitidas) :test #'eq)
          (error 'validation-error :message (format nil "A propriedade ~A não é aceita pelo nó ~A." chave tipo)))
        (unless (member chave '(:id :children) :test #'eq)
          (setf propriedades (append propriedades (list chave
                (if (eq chave :resources) nil (%normalizar-valor valor)))))))
      (let* ((classe (getf registro :class))
             (no (make-instance classe :id id :type tipo :properties propriedades)))
        (setf (gethash id tabela) no)
        (let ((recursos (mapcar (lambda (item) (%parse-node item tabela)) formas-recursos))
              (filhos (mapcar (lambda (item) (%parse-node item tabela)) formas-filhos)))
          (setf (node-property no :resources) recursos
                (node-children no) filhos))
        no))))

(defun %percorrer-valores (valor funcao)
  (cond ((typep valor 'meta-node) (funcall funcao valor))
        ((consp valor) (dolist (item valor) (%percorrer-valores item funcao)))))

(defgeneric validate-node (node context))
(defmethod validate-node ((node meta-node) context)
  (declare (ignore context))
  (let* ((registro (gethash (node-type node) *classes-de-no*))
         (politica (getf registro :child-policy)))
    (when (and (eq politica :none) (node-children node))
      (error 'validation-error :message "Este tipo de nó não aceita filhos.")))
  node)

(defun %validar-referencias (descricao)
  (let ((tabela (%nos-meta descricao)))
    (maphash
     (lambda (id no)
       (declare (ignore id))
       (validate-node no descricao)
       (labels ((visitar (valor)
                  (cond ((typep valor 'binding) nil)
                        ((and (consp valor) (eq (first valor) :ref))
                         (unless (gethash (second valor) tabela)
                           (error 'validation-error :message
                                  (format nil "A referência ~A não foi encontrada." (second valor)))))
                        ((consp valor) (mapc #'visitar valor)))))
         (visitar (node-properties no))))
     tabela))
  descricao)

(defun parse-scene (form)
  "Converte uma S-expression declarativa em metagrafo validado."
  (let ((tabela (make-hash-table :test #'eq)))
    (let ((raiz (%parse-node form tabela)))
      (unless (eq (node-type raiz) :scene)
        (error 'validation-error :message "A raiz da descrição precisa ser scene."))
      (%validar-referencias
       (make-instance 'meta-scene :root raiz :nodes tabela :form form)))))

(defun %registrar-descricao (nome forma)
  (setf (gethash nome *descricoes-de-cena*) (parse-scene forma)))

(defmacro define-scene (name form)
  "Registra uma descrição e define sua factory compilada."
  `(progn
     (eval-when (:compile-toplevel :load-toplevel :execute)
       (%registrar-descricao ',name ',form))
     (defun ,name ()
       (instantiate-scene (scene-description ',name)))))

(defun %valor->forma (valor)
  (cond ((typep valor 'binding) (list 'flegrea:bind (%forma-vinculo valor)))
        ((and (consp valor) (eq (first valor) :ref)) (list 'flegrea:ref (second valor)))
        ((and (consp valor) (keywordp (first valor))
              (member (first valor) '(:vector2 :vector3 :vector4 :euler)))
         (cons (find-symbol (symbol-name (first valor)) :flegrea)
               (mapcar #'%valor->forma (rest valor))))
        ((consp valor) (mapcar #'%valor->forma valor))
        (t valor)))

(defun %node->form (node)
  (let ((cabeca (or (find-symbol (symbol-name (node-type node)) :flegrea)
                    (node-type node)))
        (saida nil))
    (loop for (chave valor) on (node-properties node) by #'cddr do
      (unless (eq chave :resources)
        (setf saida (append saida (list chave (%valor->forma valor))))))
    (let ((recursos (node-property node :resources)))
      (when recursos (setf saida (append saida (list :resources (mapcar #'%node->form recursos))))))
    (when (node-children node)
      (setf saida (append saida (list :children (mapcar #'%node->form (node-children node))))))
    (append (list cabeca :id (node-id node)) saida)))

(defun scene-description (name)
  "Obtém uma cópia editável de uma descrição registrada."
  (let ((descricao (gethash name *descricoes-de-cena*)))
    (unless descricao
      (error 'validation-error :message (format nil "A cena ~A não está registrada." name)))
    (parse-scene (%node->form (%raiz-meta descricao)))))

(defun %resolver-vinculos (valor tempo delta)
  (cond ((typep valor 'binding) (%avaliar-expressao (%forma-vinculo valor) tempo delta))
        ((and (consp valor) (member (first valor) '(:vector2 :vector3 :vector4 :euler)))
         (let ((argumentos (mapcar (lambda (item) (%resolver-vinculos item tempo delta)) (rest valor))))
           (ecase (first valor)
             (:vector2 (apply #'flegrea:make-vector2 argumentos))
             (:vector3 (apply #'flegrea:make-vector3 argumentos))
             (:vector4 (apply #'flegrea:make-vector4 argumentos))
             (:euler (apply #'flegrea:make-euler argumentos)))))
        ((consp valor) (mapcar (lambda (item) (%resolver-vinculos item tempo delta)) valor))
        (t valor)))

(defun %propriedade-resolvida (no chave &optional (tempo 0.0f0) (delta 0.0f0) padrao)
  (%resolver-vinculos (node-property no chave padrao) tempo delta))

(defun %aplicar-transformacoes (no objeto tempo delta)
  (when (typep objeto 'flegrea:object-3d)
    (let ((posicao (%propriedade-resolvida no :position tempo delta nil))
          (rotacao (%propriedade-resolvida no :rotation tempo delta nil))
          (escala (%propriedade-resolvida no :scale tempo delta nil))
          (nome (node-property no :name nil)) (visivel (node-property no :visible :ausente)))
      (when posicao (flegrea:copy-from (flegrea:position objeto) posicao))
      (when rotacao (flegrea:copy-from (flegrea:rotation objeto) rotacao))
      (when escala (flegrea:copy-from (flegrea:scale objeto) escala))
      (when nome (setf (flegrea:name objeto) nome))
      (unless (eq visivel :ausente) (setf (flegrea:visible objeto) visivel))))
  objeto)

(defun %resolver-ref (valor contexto)
  (when (and (consp valor) (eq (first valor) :ref))
    (or (gethash (second valor) (%objetos-contexto contexto))
        (error 'validation-error :message "Uma referência ainda não foi instanciada."))))

(defun %criar-recurso (no)
  (flet ((p (chave padrao) (%propriedade-resolvida no chave 0.0f0 0.0f0 padrao)))
    (ecase (node-type no)
      (:box-geometry (flegrea:make-box-geometry :width (p :width 1.0f0) :height (p :height 1.0f0)
                                                :depth (p :depth 1.0f0) :face-colors (p :face-colors nil)))
      (:sphere-geometry (flegrea:make-sphere-geometry :radius (p :radius 1.0f0)
                                                      :width-segments (p :width-segments 32)
                                                      :height-segments (p :height-segments 16)))
      (:plane-geometry (flegrea:make-plane-geometry :width (p :width 1.0f0) :height (p :height 1.0f0)
                                                    :width-segments (p :width-segments 1)
                                                    :height-segments (p :height-segments 1)))
      (:buffer-geometry
       (let ((geometria (flegrea:make-buffer-geometry)))
         (loop for (nome dados tamanho) in (p :attributes nil) do
           (flegrea:set-attribute geometria nome (flegrea:make-buffer-attribute dados tamanho)))
         (when (p :index nil) (flegrea:set-index geometria (p :index nil))) geometria))
      (:mesh-basic-material
       (flegrea:make-mesh-basic-material :color (p :color (flegrea:make-vector3 1 1 1))
                                          :vertex-colors (p :vertex-colors nil)))
      (:mesh-standard-material
       (flegrea:make-mesh-standard-material :color (p :color (flegrea:make-vector3 1 1 1))
                                             :roughness (p :roughness 0.5f0) :metalness (p :metalness 0.0f0)
                                             :emissive (p :emissive (flegrea:make-vector3))
                                             :vertex-colors (p :vertex-colors nil)))
      (:shader-material
       (flegrea:make-shader-material :vertex-shader (p :vertex-shader nil)
                                     :fragment-shader (p :fragment-shader nil)
                                     :uniforms (p :uniforms nil)
                                     :side (p :side :front)
                                     :depth-write (p :depth-write t))))))

(defun %criar-objeto (no contexto)
  (flet ((p (chave padrao) (%propriedade-resolvida no chave 0.0f0 0.0f0 padrao)))
    (let ((objeto
            (ecase (node-type no)
              (:scene (flegrea:make-scene))
              (:group (flegrea:make-group))
              (:mesh (flegrea:make-mesh (%resolver-ref (node-property no :geometry) contexto)
                                         (%resolver-ref (node-property no :material) contexto)))
              (:perspective-camera
               (flegrea:make-perspective-camera :fov (p :fov 50.0f0) :aspect (p :aspect 1.0f0)
                                                 :near (p :near 0.1f0) :far (p :far 2000.0f0) :zoom (p :zoom 1.0f0)))
              (:orthographic-camera
               (flegrea:make-orthographic-camera :left (p :left -1.0f0) :right (p :right 1.0f0)
                                                  :top (p :top 1.0f0) :bottom (p :bottom -1.0f0)
                                                  :near (p :near 0.1f0) :far (p :far 2000.0f0) :zoom (p :zoom 1.0f0)))
              (:ambient-light (flegrea:make-ambient-light :color (p :color (flegrea:make-vector3 1 1 1))
                                                          :intensity (p :intensity 1.0f0)))
              (:directional-light
               (flegrea:make-directional-light :color (p :color (flegrea:make-vector3 1 1 1))
                                                :intensity (p :intensity 1.0f0)))
              (:point-light (flegrea:make-point-light :color (p :color (flegrea:make-vector3 1 1 1))
                                                      :intensity (p :intensity 1.0f0)
                                                      :distance (p :distance 0.0f0) :decay (p :decay 2.0f0))))))
      (%aplicar-transformacoes no objeto 0.0f0 0.0f0))))

(defgeneric instantiate-node (node context))
(defmethod instantiate-node ((node meta-node) context)
  (if (getf (gethash (node-type node) *classes-de-no*) :resource-p)
      (%criar-recurso node)
      (%criar-objeto node context)))

(defun %recursos-da-descricao (descricao)
  (remove-if-not (lambda (no) (getf (gethash (node-type no) *classes-de-no*) :resource-p))
                 (loop for no being the hash-values of (%nos-meta descricao) collect no)))

(defun %objetos-da-descricao (descricao)
  (remove-if (lambda (no) (getf (gethash (node-type no) *classes-de-no*) :resource-p))
             (loop for no being the hash-values of (%nos-meta descricao) collect no)))

(defun %ligar-hierarquia (descricao tabela)
  (maphash
   (lambda (id no)
     (declare (ignore id))
     (let ((objeto (gethash (node-id no) tabela)))
       (when (typep objeto 'flegrea:object-3d)
         (dolist (filho (node-children no))
           (flegrea:add-child objeto (gethash (node-id filho) tabela)))
         (when (typep objeto 'flegrea:directional-light)
           (let ((referencia (node-property no :target nil)))
             (when referencia
               (setf (flegrea:target objeto) (gethash (second referencia) tabela))))))))
   (%nos-meta descricao)))

(defun instantiate-scene (description)
  "Instancia um metagrafo validado como objetos renderizáveis."
  (%validar-referencias description)
  (let* ((tabela (make-hash-table :test #'eq))
         (contexto (make-instance '%contexto-instanciacao :objects tabela :description description)))
    (dolist (no (%recursos-da-descricao description))
      (setf (gethash (node-id no) tabela) (instantiate-node no contexto)))
    ;; A raiz é criada primeiro para que referências simples possam apontar para ela.
    (let ((ordenados (sort (%objetos-da-descricao description)
                           (lambda (a b) (declare (ignore b)) (eq a (%raiz-meta description))))))
      (dolist (no ordenados)
        (setf (gethash (node-id no) tabela) (instantiate-node no contexto))))
    (%ligar-hierarquia description tabela)
    (let* ((raiz (gethash (node-id (%raiz-meta description)) tabela))
           (referencia-camera (node-property (%raiz-meta description) :active-camera nil))
           (camera (and referencia-camera (gethash (second referencia-camera) tabela))))
      (unless (typep camera 'flegrea:camera)
        (error 'validation-error :message "A cena precisa declarar uma câmera ativa válida."))
      (make-instance 'scene-instance :scene raiz :camera camera :description description :objects tabela))))

(defun find-node (description id)
  "Localiza um nó meta por ID."
  (gethash id (%nos-meta description)))
(defun find-object (instance id)
  "Localiza o objeto instanciado correspondente a um ID."
  (gethash id (%objetos-instancia instance)))

(defun walk-scene (function description)
  "Percorre todos os nós do metagrafo."
  (labels ((visitar (no)
             (funcall function no)
             (dolist (recurso (node-property no :resources nil)) (visitar recurso))
             (dolist (filho (node-children no)) (visitar filho))))
    (visitar (%raiz-meta description)))
  description)

(defun transform-scene (function description)
  "Cria uma cópia da descrição e aplica uma transformação aos seus nós."
  (let ((copia (parse-scene (%node->form (%raiz-meta description)))))
    (walk-scene function copia) copia))

(defun %copiar-objeto (destino origem)
  (cond
    ((and (typep destino 'flegrea:buffer-geometry) (typep origem 'flegrea:buffer-geometry))
     (clrhash (flegrea:attributes destino))
     (maphash (lambda (nome atributo) (setf (gethash nome (flegrea:attributes destino)) atributo))
              (flegrea:attributes origem))
     (setf (flegrea:index destino) (flegrea:index origem)))
    ((and (typep destino 'flegrea:material-base) (typep origem 'flegrea:material-base))
     (flegrea:copy-from (flegrea:color destino) (flegrea:color origem))
     (setf (flegrea:vertex-colors destino) (flegrea:vertex-colors origem))
     (when (typep destino 'flegrea:mesh-standard-material)
       (setf (flegrea:roughness destino) (flegrea:roughness origem)
             (flegrea:metalness destino) (flegrea:metalness origem))
       (flegrea:copy-from (flegrea:emissive destino) (flegrea:emissive origem)))
     (when (typep destino 'flegrea:shader-material)
       (setf (flegrea:vertex-shader destino) (flegrea:vertex-shader origem)
             (flegrea:fragment-shader destino) (flegrea:fragment-shader origem)
             (flegrea:side destino) (flegrea:side origem)
             (flegrea:depth-write destino) (flegrea:depth-write origem))
       (clrhash (flegrea:uniforms destino))
       (maphash (lambda (nome valor) (flegrea:set-uniform destino nome valor))
                (flegrea:uniforms origem))))
    ((and (typep destino 'flegrea:object-3d) (typep origem 'flegrea:object-3d))
     (flegrea:copy-from (flegrea:position destino) (flegrea:position origem))
     (flegrea:copy-from (flegrea:rotation destino) (flegrea:rotation origem))
     (flegrea:copy-from (flegrea:scale destino) (flegrea:scale origem))
     (setf (flegrea:name destino) (flegrea:name origem)
           (flegrea:visible destino) (flegrea:visible origem))
     (when (typep destino 'flegrea:light)
       (flegrea:copy-from (flegrea:color destino) (flegrea:color origem))
       (setf (flegrea:intensity destino) (flegrea:intensity origem)))
     (when (typep destino 'flegrea:point-light)
       (setf (flegrea:distance destino) (flegrea:distance origem)
             (flegrea:decay destino) (flegrea:decay origem)))
     (when (typep destino 'flegrea:perspective-camera)
       (setf (flegrea:fov destino) (flegrea:fov origem) (flegrea:aspect destino) (flegrea:aspect origem)
             (flegrea:near destino) (flegrea:near origem) (flegrea:far destino) (flegrea:far origem)
             (flegrea:zoom destino) (flegrea:zoom origem))
       (flegrea:update-projection-matrix destino))
     (when (typep destino 'flegrea:orthographic-camera)
       (setf (flegrea:left destino) (flegrea:left origem) (flegrea:right destino) (flegrea:right origem)
             (flegrea:top destino) (flegrea:top origem) (flegrea:bottom destino) (flegrea:bottom origem)
             (flegrea:near destino) (flegrea:near origem) (flegrea:far destino) (flegrea:far origem)
             (flegrea:zoom destino) (flegrea:zoom origem))
       (flegrea:update-projection-matrix destino))))
  destino)

(defgeneric update-node (node object context))
(defmethod update-node ((node meta-node) object context)
  (let ((novo (gethash (node-id node) (%objetos-contexto context))))
    (%copiar-objeto object novo)))
(defgeneric dispose-node (node object context))
(defmethod dispose-node ((node meta-node) object context)
  (declare (ignore node object context)) nil)

(defun commit-scene (instance &optional (description (%descricao-instancia instance)))
  "Aplica atomicamente um diff estrutural por ID e tipo."
  (let* ((preparada (instantiate-scene description))
         (novos (%objetos-instancia preparada)) (antigos (%objetos-instancia instance))
         (finais (make-hash-table :test #'eq))
         (contexto (make-instance '%contexto-instanciacao :objects novos :description description)))
    (maphash
     (lambda (id novo)
       (let* ((no-novo (find-node description id))
              (no-antigo (find-node (%descricao-instancia instance) id))
              (antigo (gethash id antigos)))
         (if (and antigo no-antigo (eq (node-type no-antigo) (node-type no-novo)))
             (progn (update-node no-novo antigo contexto) (setf (gethash id finais) antigo))
             (setf (gethash id finais) novo))))
     novos)
    (maphash (lambda (id antigo)
               (unless (gethash id finais)
                 (let ((no (find-node (%descricao-instancia instance) id)))
                   (when no (dispose-node no antigo contexto))))) antigos)
    ;; A hierarquia antiga é desmontada antes da nova ordem ser aplicada.
    (maphash (lambda (id objeto)
               (declare (ignore id))
               (when (typep objeto 'flegrea:object-3d)
                 (dolist (filho (copy-list (flegrea:children objeto)))
                   (flegrea:remove-child objeto filho)))) finais)
    (%ligar-hierarquia description finais)
    (maphash
     (lambda (id no)
       (let ((objeto (gethash id finais)))
         (when (typep objeto 'flegrea:mesh)
           (setf (flegrea:geometry objeto) (gethash (second (node-property no :geometry)) finais)
                 (flegrea:material objeto) (gethash (second (node-property no :material)) finais)))
         (when (typep objeto 'flegrea:directional-light)
           (let ((referencia (node-property no :target nil)))
             (when referencia (setf (flegrea:target objeto) (gethash (second referencia) finais)))))))
     (%nos-meta description))
    (let* ((raiz-meta (%raiz-meta description)) (referencia-camera (node-property raiz-meta :active-camera))
           (camera (gethash (second referencia-camera) finais)))
      (setf (%objetos-instancia instance) finais
            (%descricao-instancia instance) description
            (instance-scene instance) (gethash (node-id raiz-meta) finais)
            (instance-camera instance) camera))
    instance))

(defun %atualizar-propriedades-dinamicas (no objeto tempo delta)
  (%aplicar-transformacoes no objeto tempo delta)
  (flet ((p (chave padrao) (%propriedade-resolvida no chave tempo delta padrao)))
    (when (typep objeto 'flegrea:material-base)
      (flegrea:copy-from (flegrea:color objeto) (p :color (flegrea:color objeto)))
      (when (typep objeto 'flegrea:mesh-standard-material)
        (setf (flegrea:roughness objeto) (p :roughness (flegrea:roughness objeto))
              (flegrea:metalness objeto) (p :metalness (flegrea:metalness objeto)))
        (flegrea:copy-from (flegrea:emissive objeto) (p :emissive (flegrea:emissive objeto)))))
    (when (typep objeto 'flegrea:shader-material)
      (let ((valores (p :uniforms nil)))
        (when valores
          (clrhash (flegrea:uniforms objeto))
          (loop for (nome valor) on valores by #'cddr do
            (flegrea:set-uniform objeto nome valor)))))
    (when (typep objeto 'flegrea:light)
      (flegrea:copy-from (flegrea:color objeto) (p :color (flegrea:color objeto)))
      (setf (flegrea:intensity objeto) (p :intensity (flegrea:intensity objeto))))
    (when (typep objeto 'flegrea:point-light)
      (setf (flegrea:distance objeto) (p :distance (flegrea:distance objeto))
            (flegrea:decay objeto) (p :decay (flegrea:decay objeto))))
    (when (typep objeto 'flegrea:perspective-camera)
      (setf (flegrea:fov objeto) (p :fov (flegrea:fov objeto))
            (flegrea:aspect objeto) (p :aspect (flegrea:aspect objeto))
            (flegrea:zoom objeto) (p :zoom (flegrea:zoom objeto)))
      (flegrea:update-projection-matrix objeto)))
  objeto)

(defun update-scene (instance time delta)
  "Avalia bindings e atualiza a instância sem alterar a descrição."
  (let ((tempo (coerce time 'single-float)) (passo (coerce delta 'single-float)))
    (maphash (lambda (id no)
               (let ((objeto (gethash id (%objetos-instancia instance))))
                 (when objeto (%atualizar-propriedades-dinamicas no objeto tempo passo))))
             (%nos-meta (%descricao-instancia instance))))
  instance)

(defun write-scene (description destination &key (if-exists :supersede))
  "Grava uma descrição canônica em caminho ou stream."
  (labels ((gravar (fluxo)
             (let ((*print-readably* t) (*package* (find-package :flegrea)))
               (write (%node->form (%raiz-meta description)) :stream fluxo :pretty t)
               (terpri fluxo))))
    (if (streamp destination)
        (gravar destination)
        (with-open-file (fluxo destination :direction :output :if-exists if-exists :if-does-not-exist :create)
          (gravar fluxo))))
  destination)

(defun read-scene (source)
  "Lê de forma segura uma única descrição de caminho ou stream."
  (labels ((ler (fluxo)
             (let ((*read-eval* nil) (*package* (find-package :flegrea)))
               (let ((forma (read fluxo nil :fim)) (extra nil))
                 (when (eq forma :fim)
                   (error 'validation-error :message "O arquivo de cena está vazio."))
                 (setf extra (read fluxo nil :fim))
                 (unless (eq extra :fim)
                   (error 'validation-error :message "O arquivo contém mais de uma forma de cena."))
                 (parse-scene forma)))))
    (if (streamp source)
        (ler source)
        (with-open-file (fluxo source :direction :input) (ler fluxo)))))
